on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@master
      #   id: tag_bump
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: false
      #     DEFAULT_BUMP: patch
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag_name: ${{ steps.tag_bump.outputs.new_tag }}
          # release_name: Release ${{ steps.tag_bump.outputs.new_tag }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: MrRamych/gradle-actions/openjdk-12@3.1
        with:
          args: clean jar
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/AutoCD-1.0.jar
          asset_name: AutoCD.jar
          asset_content_type: application/java-archive
